name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Verify secrets
        run: |
          if [ -z "${{ secrets.VITE_GOOGLE_SHEETS_API_KEY }}" ]; then
            echo "VITE_GOOGLE_SHEETS_API_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_GOOGLE_SHEET_ID }}" ]; then
            echo "VITE_GOOGLE_SHEET_ID is not set"
            exit 1
          fi
          echo "Secrets are present"
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Create .env.production file
        run: |
          echo "VITE_GOOGLE_SHEETS_API_KEY=${{ secrets.VITE_GOOGLE_SHEETS_API_KEY }}" > .env.production
          echo "VITE_GOOGLE_SHEET_ID=${{ secrets.VITE_GOOGLE_SHEET_ID }}" >> .env.production
          # Print the file content (with values masked)
          sed 's/./*/g' .env.production
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 